# Use the official Node.js 16 Alpine image as the base image
FROM node:16-alpine

# Set the working directory to /app
WORKDIR '/app'

# Copy the package.json and package-lock.json files to the working directory
COPY package.json .
COPY package-lock.json .

# Install the dependencies defined in package.json
RUN npm install

# Copy the entire application directory to the working directory
COPY . .

# Set the command to run the application using npm run start
CMD ["npm", "run", "start"]